"""Smart Expense Tracker API.

A small REST API for tracking personal expenses: add, list, filter by
category, compute totals, and delete. Data is persisted to a local JSON
file (no database required).
"""

import os
from typing import List, Optional

from fastapi import Depends, FastAPI, HTTPException, Query

from .models import Expense, ExpenseCreate
from .storage import ExpenseStorage

app = FastAPI(
    title="Smart Expense Tracker API",
    description="A simple REST API to add, view, filter, total, and delete personal expenses.",
    version="1.0.0",
)

# Storage is created once at import time and exposed through a dependency
# so tests can override it with an isolated temp-file-backed instance
# instead of touching the real data.json on disk.
_storage = ExpenseStorage(os.environ.get("EXPENSES_DATA_FILE", "data.json"))


def get_storage() -> ExpenseStorage:
    return _storage


@app.post("/expenses", response_model=Expense, status_code=201)
def add_expense(expense: ExpenseCreate, storage: ExpenseStorage = Depends(get_storage)):
    """Add a new expense. The id is generated by the server."""
    return storage.add_expense(
        title=expense.title,
        amount=expense.amount,
        category=expense.category,
        date=expense.date,
    )


@app.get("/expenses", response_model=List[Expense])
def list_expenses(
    category: Optional[str] = Query(None, description="Filter results by category (case-insensitive)"),
    storage: ExpenseStorage = Depends(get_storage),
):
    """View all expenses, optionally filtered by category."""
    return storage.get_all(category)


@app.get("/expenses/total")
def get_total(
    category: Optional[str] = Query(None, description="Restrict the total to a single category"),
    storage: ExpenseStorage = Depends(get_storage),
):
    """Total expenses overall, or for a single category if provided."""
    return {"category": category, "total": storage.total(category)}


@app.get("/expenses/totals-by-category")
def totals_by_category(storage: ExpenseStorage = Depends(get_storage)):
    """Total expenses broken down by every category."""
    return storage.totals_by_category()


@app.get("/expenses/monthly-summary")
def monthly_summary(storage: ExpenseStorage = Depends(get_storage)):
    """Bonus endpoint: total expenses grouped by calendar month (YYYY-MM)."""
    return storage.monthly_summary()


@app.get("/expenses/{expense_id}", response_model=Expense)
def get_expense(expense_id: int, storage: ExpenseStorage = Depends(get_storage)):
    """Fetch a single expense by id. Returns 404 if it doesn't exist.

    NOTE: this is declared after /expenses/total, /expenses/totals-by-category,
    and /expenses/monthly-summary on purpose. FastAPI matches routes in
    declaration order, so if this were declared first, a request to
    /expenses/total would try to parse "total" as the int expense_id and
    fail, instead of ever reaching the real total endpoint.
    """
    expense = storage.get_by_id(expense_id)
    if expense is None:
        raise HTTPException(status_code=404, detail=f"Expense with id {expense_id} not found")
    return expense


@app.delete("/expenses/{expense_id}", status_code=204)
def delete_expense(expense_id: int, storage: ExpenseStorage = Depends(get_storage)):
    """Delete an expense by id. Returns 404 if it doesn't exist."""
    if not storage.delete_expense(expense_id):
        raise HTTPException(status_code=404, detail=f"Expense with id {expense_id} not found")
